---
- name: Install Homebrew packages
  community.general.homebrew:
    name:
      - bat
      - bottom
      - broot
      - cantino/mcfly/mcfly
      - coreutils
      - dive
      - dog
      - duf
      - dust
      - exa
      - gawk
      - glances
      - gping
      - koekeishiya/formulae/skhd
      - ripgrep
      - hudochenkov/sshpass/sshpass
      - tree
      - unnaturalscrollwheels
      - watch
    state: present
  # unnaturalscrollwheels fails for some reason, so ignore errors here
  ignore_errors: yes

- name: Enable skhd
  command: brew services start skhd
