---
- name: Install Homebrew packages
  community.general.homebrew:
    name:
      - bat
      - bottom
      - broot
      - cantino/mcfly/mcfly
      - coreutils
      - dive
      - dog
      - duf
      - dust
      - exa
      - gawk
      - gcc
      - glances
      - gnu-tar
      - gping
      - jq
      - poppler
      - koekeishiya/formulae/skhd
      - ripgrep
      - hudochenkov/sshpass/sshpass
      - tree
      - watch
      # The packages below fail for some reason when already installed. Others don't.
      #- amethyst
      #- kitty
      #- unnaturalscrollwheels
    state: present

- name: Enable skhd
  command: brew services start skhd
