---
- name: Set up oh-my-zsh theme
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: "^ZSH_THEME="
    line: 'ZSH_THEME="{{ oh_my_zsh_theme }}"'

- name: Install tmux plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm

- name: Install Vim plugin manager packer
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim

- name: Set up aliases and other misc. settings
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    block: |
      alias ap="no_proxy=* ansible-playbook"
      
      alias cdd="cd ~/dev"
      
      alias gs="git status"
      
      alias ll="ls -lh"
      alias ls="exa"
      
      alias vim="nvim"
      
      alias ssh="TERM=xterm-256color ssh"
      
      alias tfi="terraform init"
      alias tfp="terraform plan -out .plan"
      alias tfa="terraform apply .plan"
      
      alias tm="tmux attach || tmux"
      
      # McFly history tool
      export MCFLY_KEY_SCHEME=vim
      eval "$(mcfly init zsh)"

- name: Make sure SSH config exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    state: touch

- name: Set up SSH config
  blockinfile:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    block: |
      # Include homelab SSH config
      Include {{ ansible_env.HOME }}/dev/homelab/ansible/ssh.cfg
    insertbefore: BOF
