---
- name: Set up macOS
  hosts: localhost

  tasks:

    # Set up various system settings
    - include_tasks: include-setup-system.yml
      vars:
        oh_my_zsh_theme: agnoster

    # Install Homebrew packages
    - include_tasks: include-install-packages-macos.yml
      tags: homebrew

    # Copy dotfiles to their location
    - name: Deploy dotfiles
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
      with_items:
        - { src: kitty, dst: "{{ ansible_env.HOME }}/.config/" }
        - { src: nvim, dst: "{{ ansible_env.HOME }}/.config/" }
        - { src: .tmux.conf, dst: "{{ ansible_env.HOME }}/" }
        - { src: .skhdrc, dst: "{{ ansible_env.HOME }}/" }
