alias ap="no_proxy=* ansible-playbook"
alias ag="ansible-galaxy"
alias cdd="cd ~/dev"
alias gs="git status"
alias j="just"
alias ls="eza"
alias sauron="miiocli roborockvacuum --ip 192.168.104.35 --token SEE-KEEPASS"
alias ssh="TERM=xterm-256color ssh"
alias tfi="tofu init"
alias tfp="tofu plan -out .plan"
alias tfa="tofu apply .plan"
alias tm="tmux attach || tmux"
alias v="~/.config/vault/v.sh"
alias vdown="vagrant halt"
alias vim="nvim"
alias vup="vagrant up"
alias yay="paru"
